name: Terraform Deploy
on: [push]

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    container:
      image: fredsilvas/container_terraform_aws_cli
    steps:
      - uses: actions/checkout@v2
      - name: Cache Terraform
        uses: actions/cache@v1
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache
          restore-keys: ${{ runner.os }}-terraform-plugin-cache      
      - name: Run Terraform Init
        run: terraform init
        continue-on-error: false


  terraform-validate:
    runs-on: ubuntu-latest
    needs: [terraform-init]
    container:
      image: fredsilvas/container_terraform_aws_cli
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache Terraform
        uses: actions/cache@v1
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache
          restore-keys: ${{ runner.os }}-terraform-plugin-cache
      - name: Run Terraform Validate
        run: terraform validate
        continue-on-error: false

  terraform-plan:
    runs-on: ubuntu-latest
    needs: [terraform-validate]
    container:
      image: fredsilvas/container_terraform_aws_cli
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache Terraform
        uses: actions/cache@v1
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache
          restore-keys: ${{ runner.os }}-terraform-plugin-cache
      - name: Run Terraform Plan
        run: terraform plan -out tf.plan
        continue-on-error: false        
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: artifact
      #     path: public        

  terraform-apply:
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    container:
      image: fredsilvas/container_terraform_aws_cli
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache Terraform
        uses: actions/cache@v1
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugin-cache
          restore-keys: ${{ runner.os }}-terraform-plugin-cache
      - name: Run Terraform Apply
        run: terraform apply tf.plan
        continue-on-error: false